config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: "registrations" }

  get '/group_rec', to: 'pages#group_rec'  # Matt's temporary page
  get '/mentor_info', to: 'pages#mentor_info'  # Yumi's temporary page
  get '/mentor_form', to: 'pages#mentor_form'  # Matt's temporary page
  get '/mentor_rec', to: 'pages#mentor_rec'  # Matt's temporary page
  get '/mentoree_show', to: 'pages#mentoree_show'  # Matt's temporary page


  resources :groups, only: [:index, :new, :create, :show] do
    member do
      post :join
      delete :leave
      get :users
    end
    resources :messages, only: :create
  end

  resource :mentorship do
    post :join
    get :find
    get :mentor_message
  end

  resource :group_users, only: [:create, :destroy]
  resource :profile, only: [:edit, :update]
  resource :mentor_profile, only: [:edit, :update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :group_type, presence: true
  validate :valid_group_types
  validates :post_code, presence: true, if: :parent_community?
  validates :due_date, presence: true, if: :parent_community?

  private

  def valid_group_types
    allowed_group_types = ['parent community', 'private messaging', 'mentor']
    unless allowed_group_types.include?(self.group_type)
      errors.add(:group_type, "must be one of: #{allowed_group_types.join(', ')}")
    end
  end

  def parent_community?
    group_type == 'parent community'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group, only: [:show, :join, :leave, :users]
  before_action :authorize_access, only: [:show]

  def index
    groups = Group.where(group_type: "parent community").where.not(post_code: nil)
    @relevant_groups = groups.min_by(3) do |group|
      (group.post_code - current_user.post_code).abs
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.users << current_user
    if @group.save
      redirect_to @group, notice: "New parent community group was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @group_type = @group.group_type
    if @group_type == "mentor"
      group_user_ids = @group.group_users.pluck(:user_id)
      @group_chat_mentor = User.where(id: group_user_ids).excluding(current_user).first
    end
    @message = Message.new
  end

  def join
    current_user.groups << @group
    redirect_to @group
  end

  def leave
    if @group.group_type == "parent community"
      current_user.groups.delete(@group)
      redirect_to groups_path
    else
      if current_user.is_mentor?
        current_user.mentee&.update(mentor: nil)
        current_user.update(mentee: nil)
      end
      unless current_user.is_mentor?
        current_user.mentor&.update(mentee: nil)
        current_user.update(mentor: nil)
      end
      @group.destroy
      redirect_to root_path
    end
  end

  def users
    @users = @group.users
  end

  private

  def find_group
    @group = Group.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def authorize_access
    find_group
    return if @group.users.include?(current_user)

    flash[:alert] = "You aren't a member of this group."
    redirect_to root_path
  end

  def group_params
    params.require(:group).permit(:name, :post_code, :due_date)
  end

  def configure_navbar_visibility
    @show_navbar = true
  end

end

app/views/groups/_mentor_group.html.erb
<div class="dashboard-lhs-all">
  <h2 class="two-color-sentence">together<span class="nest-purple">nest</span></h2>
  <p class="sml-dashboard-title-purple">private mentor outreach</p>

  <div class="dashboard-row">
      <div class="mentor-msg-workaround" data-controller="group-subscription" data-group-subscription-group-id-value="<%= @group.id %>" data-group-subscription-current-user-id-value="<%= current_user.id %>">
            <h1 class="two-color-sentence-sml">mentor<span class="nest-purple-sml">/mentoree</span> (private chat)</h1>
            <div class="messages" data-group-subscription-target="messages">
              <% @group.messages.each do |message| %>
              <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
                <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
                  <%= render "messages/message", message: message %>
                </div>
              </div>
              <% end %>
            </div>

            <%= simple_form_for [@group, @message],
            html: { data: { action: "turbo:submit-end->group-subscription#resetForm" }, class: "d-flex" } do |f| %>
            <%= f.input :content,
            label: false,
            placeholder: "Message ##{@group.name}",
            wrapper_html: {class: "flex-grow-1"}
          %>
          <%= f.submit "send", class: "btn btn-primary mb-3" %>
          <% end %>
          </div>

    <div>

      <div class="mentor-chat-card">
      <h2 class="two-color-sentence-sml">mentor<span class="nest-purple-sml">program</span></h2>
      <p>This is a dedicated and private space for you to communicate <br> 1-on-1 with <%= @group_chat_mentor.first_name %></p>
      <%= cl_image_tag @group_chat_mentor.photo.key, class: "mentor-chat-avatar" %>
      <h1 class="name-title"><%= @group_chat_mentor.first_name %></h1>
      <h5 class="sml-nickname"><%= @group_chat_mentor.nickname %></h5>
      </div>

      <%= image_tag asset_path("vector-directory.svg") %>

      <div class="return-box">
        <%= link_to "Community dashboard", group_path(current_user.groups.where(group_type: "parent community").first) %>
      </div>

      <div class="move-up-115px">
        <%= image_tag asset_path("vector-opt-out.svg") %>
          <div class="opt-out-box">
            <%= link_to "opt out ?", leave_group_path(@group),
            data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to permanently end this mentoring arrangement?" }%>
          </div>
      </div>

      </div>

    </div>
  </div>
</div>

<div class="tree-bg-mentor-dashboard">
</div>

app/views/groups/_parent_community.html.erb
<div class="dashboard-lhs-all">
  <h2 class="two-color-sentence">together<span class="nest-purple">nest</span></h2>
  <p class="sml-dashboard-title-purple"><%= @group.name.downcase%> / <%= @group.due_date %> bubs </p>

  <div class="dashboard-row">
    <div class="group-msg-workaround" data-controller="group-subscription" data-group-subscription-group-id-value="<%= @group.id %>" data-group-subscription-current-user-id-value="<%= current_user.id %>">
      <h1 class="two-color-sentence-sml">community<span class="nest-purple-sml">notice</span>board</h1>
      <div class="messages" data-group-subscription-target="messages">
        <% @group.messages.each do |message| %>
        <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
          <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
            <%= render "messages/message", message: message %>
          </div>
        </div>
        <% end %>
      </div>

      <%= simple_form_for [@group, @message],
      html: { data: { action: "turbo:submit-end->group-subscription#resetForm" }, class: "d-flex" } do |f| %>
      <%= f.input :content,
      label: false,
      placeholder: "Message ##{@group.name}",
      wrapper_html: {class: "flex-grow-1"} %>
      <%= f.submit "send", class: "btn btn-primary mb-3" %>
      <% end %>
    </div>

    <div>
      <%= image_tag asset_path("vector-mentorship.svg") %>

      <div class="mentorship-box">
        <h2 class="two-color-sentence-sml">mentor<span class="nest-purple-sml">program</span></h2>
        <p>Access your uniquely tailored mentorship opportunities <%= link_to "here", mentorship_path %></p>
      </div>

      <div class="directory-box">
        <h2 class="two-color-sentence-sml"><span class="nest-purple-sml">directory</span></h2>
        <p>See all the lovely people in your community group <%= link_to "here", users_group_path %></p>
      </div>

      <%= image_tag asset_path("vector-directory.svg") %>

      <div class="links-box">
        <%= link_to "Leave group ?", leave_group_path(@group),
        data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to permanently leave this group?" }%>
      </div>
    </div>
  </div>
</div>

<div class="tree-bg-dashboard"></div>

app/views/groups/index.html.erb
<div class="form-flexbox-lhs">
  <div class="half-page-wider">
    <h2 class="two-color-headline">group<span class="nest-purple">placement</span></h2>
    <p>Based on your profile we can determine the best 3 parent community options for you to join. The following parent communities are recommended to you because the members are based in your general area and, importantly, the due dates / birth dates of their babies align with yours – an important factor for peer support, understanding and relating to one another.</p>

    <div style="display: flex; justify-content: space-between;">
      <% @relevant_groups.each do |group| %>
        <div class="group-rec-card">
          <%= image_tag asset_path("tree-thumbnail.png"), class: "tn-avatar-lg-purple" %>
          <h2><%= group.name.downcase %></h2>
          <h6><%= group.post_code %></h6>
          <% if current_user.groups.include?(group) %>
            <p>You're already<br>a part of<br>this group</p>
          <% else %>
            <%= button_to "join", join_group_path(group), class: "card-link" %>
          <% end %>
        </div>
      <% end %>
    </div>

    <p>A supportive space where you can share advice, moral support, and laughter is within reach.</p>
    <p>Otherwise, you can start your very own parent community <%= link_to "here", new_group_path %></p>
    <p>Not interested in joining a togthernest community group today? Click <%= link_to "here", root_path %></p>
  </div>
</div>

<div class="tree-bg-group-rec"></div>

app/views/groups/new.html.erb
<div class="form-flexbox-lhs">
  <div class="white-form-rounded">
  <p class="two-color-headline">new<span class="nest-purple">parent community</span></p>
  <p>Can't find the right match for you? There's always a solution at togethernest. Fill in this short form to create a new parent community in your area. Then just wait for other parents to join. We look forward to welcoming you and fellow new members into the nest.</p>

  <%= simple_form_for(@group) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name, label: "Your parent community's name" %>
      <%= f.input :post_code, label: "The postcode for your community's area",
                  as: :string,
                  required: true %>
      <%= f.input :due_date, label: "The season and year the babies of this community are expected to be born",
                  as: :string,
                  required: true %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "submit" %>
    </div>
  <% end %>
  </div>
</div>

<div class="tree-bg-signup">
</div>

app/views/groups/show.html.erb
<% if @group_type == "parent community" %>
  <%= render "parent_community"  %>
<% elsif @group_type == "mentor" %>
  <%= render "mentor_group"  %>
<% else %>
<% end %>

app/views/groups/users.html.erb
<div class="sml-title-purple-align-right">
  directory
</div>

<div class="two-color-sentence-align-right">
  <%= @group.name.downcase %>
</div>

<div class="group-list">
  <% @users.each do |user| %>
    <div class="parent-card">
      <%= cl_image_tag user.photo.key, class: "parent-avatar-lg"%>
      <h2><%= user.first_name %></h2>
      <p><%= user.nickname %></p>
      <p><%= user.bio %></p>
    </div>
  <% end %>
</div>

<div class="group-list">
  <div class="large-link-purple">
    <%= link_to "Return to dashboard", :back %>
  </div>
</div>

<div class="tree-bg-user-edit">
</div>