config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: "registrations" }

  get '/group_rec', to: 'pages#group_rec'  # Matt's temporary page
  get '/mentor_info', to: 'pages#mentor_info'  # Yumi's temporary page
  get '/mentor_form', to: 'pages#mentor_form'  # Matt's temporary page
  get '/mentor_rec', to: 'pages#mentor_rec'  # Matt's temporary page
  get '/mentoree_show', to: 'pages#mentoree_show'  # Matt's temporary page


  resources :groups, only: [:index, :new, :create, :show] do
    member do
      post :join
      delete :leave
      get :users
    end
    resources :messages, only: :create
  end

  resource :mentorship do
    post :join
    get :find
    get :mentor_message
  end

  resource :group_users, only: [:create, :destroy]
  resource :profile, only: [:edit, :update]
  resource :mentor_profile, only: [:edit, :update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if @show_navbar %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%# <%= image_tag asset_path("#") %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">

            </li>
            <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= cl_image_tag current_user.photo.key, class: "avatar-bordered", alt: "dropdown menu" %>
            </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%# <%= link_to "My parent group", groups(current_user.groups.first), class: "dropdown-item" %>
                <%# <%= link_to "Permanently leave my parent group", leave_group_path(@group), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to leave the mentor program?" }, class: "dropdown-item" %>
                <%= link_to "home", root_path, class: "dropdown-item" %>
                <%= link_to "profile", edit_profile_path, class: "dropdown-item" %>
                <%= link_to "account", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "sign out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "(Login test)", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>