config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: "registrations" }

  get '/group_rec', to: 'pages#group_rec'  # Matt's temporary page
  get '/mentor_info', to: 'pages#mentor_info'  # Yumi's temporary page
  get '/mentor_form', to: 'pages#mentor_form'  # Matt's temporary page
  get '/mentor_rec', to: 'pages#mentor_rec'  # Matt's temporary page
  get '/mentoree_show', to: 'pages#mentoree_show'  # Matt's temporary page


  resources :groups, only: [:index, :new, :create, :show] do
    member do
      post :join
      delete :leave
      get :users
    end
    resources :messages, only: :create
  end

  resource :mentorship do
    post :join
    get :find
    get :mentor_message
  end

  resource :group_users, only: [:create, :destroy]
  resource :profile, only: [:edit, :update]
  resource :mentor_profile, only: [:edit, :update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/pages/group_rec.html.erb
<div class="form-flexbox-rhs">
  <div class="half-page">
    <h2 class="two-color-sentence">Welcome to the <span class="nest-purple">nest</span></h2>
    <p>We are excited to welcome you to a close-knit community group of parents just like you. This group placement was carefully calculated based on criteria such as your location and the due date / birth date of your little one, ensuring you are connected with parents who can understand and relate to the journey you are on.</p>
    <h2 class="two-color-sentence">sydney<span class="nest-purple">south:</span></h2>

    <div style="display: flex; align-items: center;">
      <div class="grouped-avatar-container">
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
      </div>
      <h1 id="plus">+</h1>
      <div class="new-parent-container">
        <%= cl_image_tag current_user.photo.key, class: "tn-avatar-lg avatar" %>
      </div>
    </div>

    <p>You'll find a warm and supportive space where you can share advice, moral support, and laughter.</p>
    <p>Continue below to join the recommended community group.</p>
    <div class="btn-hp">
      <%= link_to "join", group_path(1) %>
    </div>
    <p>Not so keen? Click <%= link_to "here", root_path %></p>
  </div>
</div>

<div class="tree-bg-group-rec-accept">
</div>

app/views/pages/grouprec.html.erb
<div class="form-flexbox-rhs">
  <div class="half-page">
    <h2 class="two-color-sentence">Welcome to the <span class="nest-purple">nest</span></h2>
    <p>We are excited to welcome you to a close-knit community group of parents just like you. This group placement was carefully calculated based on criteria such as your location and the due date / birth date of your little one, ensuring you are connected with parents who can understand and relate to the journey you are on.</p>

    <div style="display: flex; align-items: center;">
      <div class="grouped-avatar-container">
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
        <%= image_tag asset_path("parent1.jpg"), class: "tn-avatar" %>
      </div>
      <h1 id="plus">+</h1>
      <div class="new-parent-container">
        <%= cl_image_tag current_user.photo.key, class: "tn-avatar-lg avatar" %>
      </div>
    </div>

    <p>You'll find a warm and supportive space where you can share advice, moral support, and laughter.</p>
    <p>Continue below to join the recommended community group.</p>
    <div class="btn-hp">
      <%= link_to "join", root_path %>
    </div>
    <p>Not so keen? Click <%= link_to "here", root_path %></p>
  </div>
</div>

<div class="tree-bg-group-rec">
</div>

app/views/pages/home.html.erb
<div class="flex-hp">
  <div id="tree-hp">
    <%= image_tag asset_path("tree.svg") %>
  </div>
  <div id="birds-logo-hp">
    <%= image_tag asset_path("birds.svg"), class: "birds-flying" %>
    <div id="logo-tagline">
      <h1>together<span class="nest">nest</span></h1>
      <p>Guiding and supporting new parents through thoughtfully<br>curated online communities and mentorships</p>
      <% if current_user && current_user.groups.where(group_type: "parent community").first %>
        <h2><%= link_to "dashboard", group_path(current_user.groups.where(group_type: "parent community").first) %> | <%= link_to 'log out', destroy_user_session_path, data: {turbo_method: :delete} %></h2>
      <% elsif current_user %>
        <h2><%= link_to "dashboard", groups_path %> |<%= link_to 'log out', destroy_user_session_path, data: {turbo_method: :delete} %></h2>

      <% else %>
        <h2><%= link_to "log in", new_user_session_path %> | <%= link_to "sign up", new_user_registration_path %></h2>
      <% end %>

    </div>
  </div>
</div>
<div class="footer-hp">
  <p>Made with love, confusion, stress, hash rockets, tears and much laughter by the good people at togethernest - Halima, Matt, Tara & Yumi.</p>
</div>
<div class="sky">
</div>

app/views/pages/mentor_form.html.erb
<div class="form-flexbox-lhs">
  <div class="white-form-rounded-wide">
    <h2 class="two-color-headline">mentor<span class="nest-purple">program</span></h2>
    <p>
      Share a brief introduction about yourself. This message will help potential mentors understand your background, interests, and what you hope to gain from a mentoring relationship. Feel free to highlight areas where you seek guidance.
    </p>
    <p>
      Your introduction will serve as the first step in connecting with mentors who can support your growth and development.
    </p>

    <%= simple_form_for(current_user, as: :user, url: profile_path, html: { method: :patch }) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">

        <%= f.input :due_date,
                    required: true,
                    as: :string,
                    input_html: { autocomplete: "due date", data: { controller: "datepicker" } }  %>
        <%= f.input :post_code,
                    required: true,
                    input_html: { autocomplete: "postcode" } %>
        <%= f.input :bio,
                    required: true,
                    input_html: { autocomplete: "short bio to introduce yourself" } %>
      </div>
      <p>  </p>
      <p>Continue below for you profile to be carefully matched to potential mentors.</p>
      <p>Your mentor options will be shown on the next page.</p>
      <div class="btn">
        <%= link_to "connect", mentor_rec_path %>
      </div>
    <% end %>

    <p>Not so keen? Click <%= link_to "here", root_path %></p>  </div>
</div>
<div class="tree-bg-mentor-form">
</div>

app/views/pages/mentor_info.html.erb
<div class="form-flexbox-rhs">
  <div class="half-page">
    <h2 class="two-color-sentence">mentor<span class="nest-purple">program</span></h2>
    <div style="display: flex; align-items: center;">
      <div class="mentor-info-container">
        <%= image_tag asset_path("parent1.jpg"), class: "mentor-info-avatar-lg" %>
      </div>
      <h1 id="plus">+</h1>
      <div class="mentor-info-container">
        <%= cl_image_tag current_user.photo.key, class: "mentor-info-avatar-lg" %>
      </div>
    </div>

    <p>
      Having a mentor can greatly benefit you in becoming a good and confident parent.
    </p>

    <p>
      A mentor provides a trusted source of guidance, support, and wisdom, offering valuable insights based on their own experiences and knowledge.
    </p>

    <p>
      They can help you navigate the challenges of parenthood, offering advice on various aspects such as child development, discipline techniques, communication skills, and self-care. A mentor can also serve as a role model, inspiring you to develop positive parenting practices and cultivate a nurturing environment for your children.
    </p>

    <p>
      Through their encouragement and feedback, a mentor empowers you to build confidence in your parenting abilities. Ultimately, having a mentor by your side can enhance your parenting journey, equipping you with the tools and encouragement needed to thrive as a parent.
    </p>

    <p>
      Continue below to join the mentorship program.
    </p>

    <div class="mentor-info-btn-container">
      <div class="mentor-info-btn-hp">
        <%= link_to "register", mentor_form_path %>
      </div>
    </div>

    <p>
      Are you interested in becoming a Mentor yourself? Click <%= link_to "here", mentor_form_path %>
    </p>
  </div>
</div>

<div class="tree-bg-mentor-info">
</div>

app/views/pages/mentor_rec.html.erb
<div class="form-flexbox-rhs">
  <div class="mentors-x3-container">
    <h2 class="two-color-sentence">your together<span class="nest-purple">nest</span><br>mentor matches</h2>
    <p>
      We're thrilled to inform you that we've identified three ideal mentor options tailored specifically to your situation. Each mentor brings unique expertise and experience. Ultimately, the decision is yours, empowering you to choose the mentor who you feel most comfortable with.
    </p>
    <div style="display: flex; justify-content: space-between;">
      <div class="mentor-card">
        <%= image_tag asset_path("parent2.jpg"), class: "mentor-info-avatar-lg" %>
        <h2>Jo</h2>
        <p>Loving mum of three cheeky boys</p>
        <div class="btn">
          <%= link_to "request", root_path %>
        </div>
      </div>
      <div class="mentor-card">
        <%= image_tag asset_path("parent3.jpg"), class: "mentor-info-avatar-lg" %>
        <h2>Billy</h2>
        <p>I'd say I'm a tough but fair dad</p>
        <div class="btn">
          <%= link_to "request", root_path %>
        </div>
      </div>
      <div class="mentor-card">
        <%= image_tag asset_path("parent1.jpg"), class: "mentor-info-avatar-lg" %>
        <h2>Emma</h2>
        <p>My kids are absolute animals</p>
        <div class="btn">
          <%= link_to "request", root_path %>
        </div>
      </div>
    </div>
    <p>
      Make your selection above and your preferred mentor will recieve your request along with your profile and introduction message. Once accepted, we will connect you.
    </p>
    <p>
      If you you do not wish to proceed at this time, please click <%= link_to "here", group_path(1) %>
    </p>
  </div>
</div>


<div class="tree-bg-mentor-rec">
</div>

app/views/pages/mentoree_show.erb
<div class="form-flexbox-rhs">
  <div class="half-page">
    <h2 class="two-color-sentence">you have a new <span class="nest-purple">mentorship</span> request</h2>
    <p>
      A new parent has requested you to mentor them on their parenthood journey. Please review their profile and take the time to consider if this is the right fit for the two of you.
    </p>

      <div class="mentoree-card">
        <div class="new-parent-container">
          <%= image_tag asset_path("parent2.jpg"), class: "tn-avatar-lg avatar" %>
        </div>
        <h2>"name"</h2>
        <p>"As a parent, I've learned that the greatest joys often come from the simplest moments. Whether it's sharing giggles over a messy finger-painting session or cuddling up for bedtime stories, every day brings new adventures and opportunities for growth. My journey through parenthood has taught me patience, resilience, and the importance of cherishing every milestone, no matter how small. Together, my family and I navigate the ups and downs of life with love, laughter, and plenty of hugs along the way"</p>
        <div class="flex">
          <div class="btn">
            <%= link_to "accept", root_path %>
          </div>
          <div class="btn">
            <%= link_to "decline", group_path(1) %>
          </div>
        </div>
      </div>

    <p>
      Click accept when you are comfortable to continue. A dedicated space will be set up for you and your mentoree to connect.
    </p>
    <p>
      To decline this invitation, please click <%= link_to "here", group_path(1) %>
    </p>
  </div>
</div>


<div class="tree-bg-mentor-rec">
</div>