config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: "registrations" }

  get '/group_rec', to: 'pages#group_rec'  # Matt's temporary page
  get '/mentor_info', to: 'pages#mentor_info'  # Yumi's temporary page
  get '/mentor_form', to: 'pages#mentor_form'  # Matt's temporary page
  get '/mentor_rec', to: 'pages#mentor_rec'  # Matt's temporary page
  get '/mentoree_show', to: 'pages#mentoree_show'  # Matt's temporary page


  resources :groups, only: [:index, :new, :create, :show] do
    member do
      post :join
      delete :leave
      get :users
    end
    resources :messages, only: :create
  end

  resource :mentorship do
    post :join
    get :find
    get :mentor_message
  end

  resource :group_users, only: [:create, :destroy]
  resource :profile, only: [:edit, :update]
  resource :mentor_profile, only: [:edit, :update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/mentorships_controller.rb
class MentorshipsController < ApplicationController
  def join
    if current_user.update(is_mentor: true)
      redirect_to edit_mentor_profile_path
    else
      redirect_to mentorship_path, notice: current_user.errors.full_messages.to_sentence
    end
  end

  def find
    mentor_users = User.where(is_mentor: true).excluding(current_user)
    @mentor_match = mentor_users.min_by(3) do |mentor_user|
      (mentor_user.post_code - current_user.post_code).abs
    end
  end

  def create
    mentor_user = User.find(params[:mentor_id])
    current_user.update(mentor: mentor_user)
    mentor_user.update(mentee: current_user)
    mentor_group = Group.create(name: "mentor/mentoree private chat", group_type: "mentor", post_code: nil)
    mentor_group.users << mentor_user
    mentor_group.users << current_user
    redirect_to mentor_group
  end

  def show
    if current_user.mentor.present? || current_user.mentee.present?
      redirect_to current_user.groups.where(group_type: "mentor").first
    elsif current_user.is_mentor == true && current_user.mentee.nil?
      redirect_to mentor_message_mentorship_path
    else
      render :show
    end
  end
end

app/views/mentorships/find.html.erb
<div class="form-flexbox-rhs">
  <div class="mentors-x3-container">
      <h2 class="two-color-sentence">your together<span class="nest-purple">nest</span><br>mentor matches</h2>
      <p>
        We're thrilled to inform you that we've identified three ideal mentor options tailored specifically to your situation. Each mentor brings unique expertise and experience. Ultimately, the decision is yours, empowering you to choose the mentor who you feel most comfortable with.
      </p>
      <div style="display: flex; justify-content: space-between;">
        <% @mentor_match.each do |mentor_user| %>
          <div class="mentor-card">
            <%= cl_image_tag mentor_user.photo.key, class: "avatar-large", alt: "user photo" %>
            <h2><%= mentor_user.first_name %></h2>
            <p><%= mentor_user.bio %></p>
            <p class="p-postcode">postcode: <%= mentor_user.post_code %></p>
            <div class="btn">
              <%= button_to "Select", mentorship_path(mentor_id: mentor_user.id) %>
            </div>
          </div>
          <% end %>
      </div>
        <p>
          Make your selection above and your preferred mentor will recieve your request along with your profile and introduction message. Once accepted, we will connect you.
        </p>
        <p>
          If you you do not wish to proceed at this time, please click <%= link_to "here", group_path(1) %>
        </p>
  </div>
</div>


<div class="tree-bg-mentor-rec">
</div>

app/views/mentorships/mentor.html.erb
<h1>Test</h1>

app/views/mentorships/mentor_message.html.erb
<div class="mentor-msg-box-all">
  <div class="half-page">
    <h2 class="two-color-sentence">mentor<span class="nest-purple">program</span></h2>
    <p>You’ve signed up to be a mentor, but there are currently no outstanding mentor requests.</p>
    <p class="extra-margin-p">Please check back later.</p>
    <div class="large-link-purple">
      <%= link_to "Return to dashboard", :back %>
    </div>
  </div>
</div>

<div class="tree-bg-mentor-info">
</div>

app/views/mentorships/show.html.erb
<div class="mentor-show-box-all">
    <div>
    <div class="hands-title">
      <div class="hands">
          <%= cl_image_tag current_user.photo.key, class: "mentor-info-avatar-lg" %>
          <%= image_tag asset_path("hands.svg"), style: "width: 100px; margin-top: -12px;" %>
      </div>
      <h2 class="two-color-sentence">mentor<span class="nest-purple">program</span></h2>
    </div>
    </div>


    <div class="columns-container">
    <div class="column">
      <p>Having a mentor can greatly benefit you in becoming a good and confident parent.</p>
      <p>
        A mentor provides a trusted source of guidance, support, and wisdom, offering valuable insights based on their own experiences and knowledge.
      </p>
      <p>
        Through their encouragement and feedback, a mentor empowers you to build confidence in your parenting abilities. Ultimately, having a mentor by your side can enhance your parenting journey, equipping you with the tools and encouragement needed to thrive as a parent.
      </p>
      <p>Continue below to join the mentorship program as a mentee.</p>

    </div>
    <div class="column">
        <p>Are you interested in becoming a Mentor?</p>
        <p>Guiding a new parent to become more confident in their parenting skills can be greatly rewarding.</p>
        <p>
          After having benefited from community and parenting support at Togethernest yourself, why not give back to the community and help someone else navigate the challenges of parenthood? You'll help us offer accessible support to parents in similar circumstances as you; support from parents for parents.
        </p>
        <p>We ask that you have at least two years experience as a parent to join Togethernest as a mentor.</p>
        <p>Continue below to join the mentorship program as a mentor.</p>

        </div>
      </div>


        <div class="columns-container">

        <div class="mentor-info-btn-container">
        <%= link_to "find a mentor", find_mentorship_path, class: "mentor-info-btn-hp"%>
        </div>

        <div class="mentor-info-btn-container">
        <%= button_to "be a mentor", join_mentorship_path, class: "mentor-info-btn-hp" %>
        </div>

      </div>

    </div>


</div>



<div class="tree-bg-mentor-info">
</div>